### ISSUE TITLE
Travel Affiliate

### ISSUE THREAD

**Issue by emgump** [affilinet/wordpress-plugin#1]
Hi,
I want to add more API type affiliate to my travel website. any suggestions?

Thank you all

**Comment by avaffilinet** [comment]
Dear emgump,

check this out: https://affiliatetheme.io/en/
It provides you with easy to use affilinet API integration via a plugin (API) and theme.

**Comment by emgump** [comment]
Hi,

Went on this site but didn't understnad how does that come up with what I need... I've asked for travel API and as far as i've seen, the website you sent me to is about selling products on my website


thoughts?


Thank you!


Regards,
Nir Kroshinsky

בברכה,
ניר קרושינסקי
________________________________

**Comment by avaffilinet** [comment]
affilinet does not provide a travel specific API, but a product data API which includes also travel products (e.g. Hotels) from travel clients. Have a closer look at our API: http://developer.affili.net/productdata-webservices or in case you use PHP also here: http://developer.affili.net/productdata-php-sdk.

Please use the customer service contact details at the developer hub for API specific questions. This github repo is about our WordPress Performance Ads product only.
