### ISSUE TITLE
Adjust/Align Backend settings appearance

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin#3]
- Align backend appearance of Performance Ads WP Plugin with new WP Plugin (Widgets) by rename "settings > affilinet" to "Settings > affilinet Perf. Ads" (short form only if it does not fit in terms of length).
- Please add "settings" link in installed plugins listing: /wp-admin/plugins.php right aside [Deactivate] Link

**Comment by avaffilinet** [comment]
Didn't the partnership dialog had a "green" icon in the older versions (see marked area with yellow rectangle)?
![2018-03-05 10_28_46-affilinet settings namibia reiseberichte wordpress](https://user-images.githubusercontent.com/3481571/36969017-9491e864-2064-11e8-929c-b590f203ebd2.png)

**Comment by rechl** [comment]
Yes, there is a icon which is working on my test sites. These icons depend on an external font (fontawesome) which is integrated via maxcdn. I now changed this and use the original Wordpress Icons (dashicons). This should then be less prone to failures.

**Comment by avaffilinet** [comment]
ok, works after update
