### ISSUE TITLE
Add Ads.txt 

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin#4]
Reselling von Inventar zukünftig programmatisch nur noch mit Ads.txt sinnvoll möglich: https://iabtechlab.com/ads-txt/
Aus diesem Grund prüfen, ob über WP Plugin auch Ads.txt für Performance Ads ausgeliefert werden kann.
Mögliches Problem: Ads.txt gehört normalerweise in Hauptpfad / der Domain.

**Comment by rechl** [comment]
Wie muss denn das ads.txt file aussehen? Wir können die Datei schon  im Root Pfad ablegen.  
Allerdings laufen wir Gefahr, dass wir eine bestehende Datei überschreiben. Es gibt auch Plugins die diese Datei ausliefern. Das kann auch zu Komplikationen führen. 

Lass uns dazu mal telefonieren...

**Comment by avaffilinet** [comment]
Please add the following Content to the ads.txt file:

appnexus.com, 8332, RESELLER, f5ab79cb980f11d1
appnexus.com, 8327, RESELLER, f5ab79cb980f11d1
appnexus.com, 8334, RESELLER, f5ab79cb980f11d1
appnexus.com, 8333, RESELLER, f5ab79cb980f11d1

**Comment by rechl** [comment]
Implemented in V1.9.1
